### ISSUE TITLE
Can find key for not selected sector

### ISSUE THREAD

**Issue by zevsariy** [aczid/crypto1_bs#26] opened 2017-10-06 18:30 UTC
When I use brute for crack sector 5(for example), I can get the key, but this key will be not for selected sector 5, It can be for sector 2,3,4. When I crack sector 3, I can get key for sector 5, not for sector 3. 
Also, when I use true key for sector 5 for cracking another sector, brute can say, that this key is not for selected sector O.o

**Comment by unkernet** [comment] 2017-10-06 18:58
You should input block number, not a sector.

**Comment by zevsariy** [comment] 2017-10-06 20:03
LOL, it is really work). Thank you. It is my mistake, I spend two weeks, before I understand it >_<

**Comment by aczid** [comment] 2017-10-15 23:52
I would have hoped the fixes in https://github.com/aczid/crypto1_bs/pull/20 would have removed this confusion by now. Happy to hear that it works as intended! :) Closing this issue.

**Closed by aczid** 2017-10-15 23:52 UTC
