### ISSUE TITLE
craptev1-v1.1 Website down

### ISSUE THREAD

**Issue by hendl** [aczid/crypto1_bs#30] opened 2018-06-26 18:08 UTC
Hi

The website http://crapto1.netgarage.org seems to be offline. 
Is there any other way to get these files?

thx

**Comment by aczid** [comment] 2018-06-26 20:16
Duplicate of https://github.com/aczid/crypto1_bs/issues/29

**Comment by aczid** [comment] 2018-06-26 20:30
Keeping this issue open for visibility.

**Comment by aczid** [comment] 2018-06-26 20:31
Duplicate of https://github.com/aczid/crypto1_bs/issues/29

**Closed by aczid** 2018-06-26 20:31 UTC

**Comment by pengxueting** [comment] 2023-02-01 09:34
> Hi
> 
> The website http://crapto1.netgarage.org seems to be offline. Is there any other way to get these files?
> 
> thx

我也没找到
