### ISSUE TITLE
 error: nfc/nfc.h: No such file or directory

### ISSUE THREAD

**Issue by arcadico** [aczid/crypto1_bs#16] opened 2017-01-08 11:38 UTC
hi in windows 10 64bit  I have this error: nfc/nfc.h: No such file or directory in Qt creator, I have configure  generate and   build it. can you help me?

**Comment by aczid** [comment] 2017-01-08 19:36
Windows is not supported.

**Comment by aczid** [comment] 2017-01-08 21:24
Duplicate of issue #15

**Closed by aczid** 2017-01-08 21:24 UTC
